import React from 'react';
import ReactMarkdown from 'react-markdown';

interface MemoPanelProps {
    memo: string;
    source: string;
}

export default function MemoPanel({ memo, source }: MemoPanelProps) {
    const handlePrint = () => {
        window.print();
    };

    return (
        <div id="memo-section" className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden animate-in fade-in zoom-in-95 duration-500">
            <div className="border-b border-slate-100 bg-slate-50/50 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <div className="p-1.5 bg-emerald-100 rounded text-emerald-700">
                        📄
                    </div>
                    <div>
                        <h3 className="text-sm font-bold uppercase tracking-wider text-slate-700">
                            Compliance Memo
                        </h3>
                        <div className="flex items-center gap-2 mt-0.5">
                            {source === "ai-enhanced" ? (
                                <span className="inline-flex items-center rounded-full bg-purple-100 px-2 py-0.5 text-[10px] font-medium text-purple-700">
                                    ✨ Gemini Enhanced
                                </span>
                            ) : (
                                <span className="inline-flex items-center rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-600">
                                    Standard Template
                                </span>
                            )}
                            <span className="text-[10px] text-slate-400">Generated {new Date().toLocaleDateString()}</span>
                        </div>
                    </div>
                </div>

                <button
                    onClick={handlePrint}
                    className="text-xs bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 px-3 py-1.5 rounded-md font-medium transition-colors shadow-sm"
                >
                    🖨️ Print / PDF
                </button>
            </div>

            <div className="p-8 bg-white">
                <div className="prose prose-sm prose-slate max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-blue-600">
                    <ReactMarkdown>{memo}</ReactMarkdown>
                </div>
            </div>

            <div className="bg-slate-50 px-6 py-3 border-t border-slate-100 text-[10px] text-slate-400 text-center">
                This document is automatically generated by N-Guard based on field inputs and local weather data.
                Not a substitute for certified agronomic advice.
            </div>
        </div>
    );
}
